# Generated by Django 2.2.28 on 2022-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
